### ISSUE TITLE
send_health_check_pass error, if rabbit.autocluster.peer_discovery_consul is missing

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-peer-discovery-consul#1]
Using the following configuration:
```
autocluster.peer_discovery_backend = rabbit_peer_discovery_consul
```
got this error:
```
Cannot discover any nodes because Consul cluster details are not configured!
2017-04-26 17:29:13.259 [error] emulator Error in process <0.659.0> on node rabbit@mac with exit value:
{{case_clause,{{[],disc},60}},[{rabbit_peer_discovery_consul,wait_nodelist,1,[{file,"src/rabbit_peer_discovery_consul.erl"},{line,516}]},{rabbit_peer_discovery_consul,send_health_check_pass,0,[{file,"src/rabbit_peer_discovery_consul.erl"},{line,490}]}]}
```

This because [{list_nodes(), N}](https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/blob/master/src/rabbit_peer_discovery_consul.erl#L516) does not mach with `{ {[], disc}, _}` 

To quick solve it is enough to add:
```
wait_nodelist(N) ->
    case {list_nodes(), N} of
        { {[], disc}, _} -> {error, "Peer discovery backend is set to....etc "};
 ```
or better [`send_health_check_pass`](https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/blob/master/src/rabbit_peer_discovery_consul.erl#L240) should not start

**Comment by michaelklishin** [comment]
I haven't gotten to the new style config mappings yet but thanks for pointing this out.
