### ISSUE TITLE
CONSUL_LOCK_PREFIX env variable not work properly

### ISSUE THREAD

**Issue by sgavrylenko** [rabbitmq/rabbitmq-peer-discovery-consul#15]
Hello!
It looks like CONSUL_LOCK_PREFIX env variable doesn't work
After adding this variable into env with value "/rabbitmq/project/env" the default path of session lock in KV doesn't changed and stay "/rabbitmq/default/startup_lock"

rabbitmq details

{running_applications,
     [{rabbitmq_peer_discovery_consul,
          "Consult-based RabbitMQ peer discovery backend","3.7.7"},
      {rabbitmq_peer_discovery_common,
          "Modules shared by various peer discovery backends","3.7.7"},
      {prometheus_rabbitmq_exporter,
          "RabbitMQ Prometheus.io metrics exporter","v3.7.2.2"},
      {rabbitmq_management,"RabbitMQ Management Console","3.7.7"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.7.7"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.7.7"},
      {rabbit,"RabbitMQ","3.7.7"},
      {os_mon,"CPO  CXC 138 46","2.4.5"},
      {amqp_client,"RabbitMQ AMQP Client","3.7.7"},
      {rabbit_common,
          "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
          "3.7.7"},
      {ranch_proxy_protocol,"Ranch Proxy Protocol Transport","1.5.0"},
      {xmerl,"XML parser","1.3.17"},
      {inets,"INETS  CXC 138 49","7.0.1"},
      {cowboy,"Small, fast, modern HTTP server.","2.2.2"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.5.0"},
      {ssl,"Erlang/OTP SSL application","9.0.1"},
      {public_key,"Public key infrastructure","1.6.1"},
      {asn1,"The Erlang ASN1 compiler version 5.0.6","5.0.6"},
      {mnesia,"MNESIA  CXC 138 12","4.15.4"},
      {recon,"Diagnostic tools for production use","2.3.2"},
      {prometheus_process_collector,
          "Prometheus.io process collector\n    Collector exports the current state of process metrics including cpu, memory,\n    file descriptor usage and native threads count as well as the process start and up times.",
          "1.3.1"},
      {cowlib,"Support library for manipulating Web protocols.","2.1.0"},
      {prometheus,"Prometheus.io client in Erlang","3.5.1"},
      {jsx,"a streaming, evented json parsing toolkit","2.8.2"},
      {crypto,"CRYPTO","4.3.2"},
      {lager,"Erlang logging framework","3.6.3"},
      {goldrush,"Erlang event stream processor","0.1.9"},
      {compiler,"ERTS  CXC 138 10","7.2.3"},
      {syntax_tools,"Syntax tools","2.1.5"},
      {syslog,"An RFC 3164 and RFC 5424 compliant logging framework.","3.4.2"},
      {sasl,"SASL  CXC 138 11","3.2"},
      {stdlib,"ERTS  CXC 138 10","3.5.1"},
      {kernel,"ERTS  CXC 138 10","6.0"}]},

**Comment by lukebakken** [comment]
> It looks like CONSUL_LOCK_PREFIX env variable doesn't work. After adding this variable into env ...

Hello!

There is no indication in your report of a bug. You have not provided any output indicating that the `CONSUL_LOCK_PREFIX` is not working, nor have you provided the complete configuration files you are using for RabbitMQ.

Please provide more information (complete log files, configuration files, debug output from Consul, etc) and post to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

If enough details and evidence are provided that demonstrate an issue we'd be happy to file one on GitHub.

Thanks again!
Luke

**Comment by michaelklishin** [comment]
Environment variables is not the recommended way of configuring things. It was all the rage in rabbitmq-autocluster and was preserved for easier migration but please use regular configuration keys from now on. There is a dedicated doc section that explains how to [verify effective configuration](http://www.rabbitmq.com/configure.html#verify-configuration-effective-configuration) which would be a required piece of evidence that a configured setting is ignored.

**Comment by sgavrylenko** [comment]
Thank you @michaelklishin 
Your advice was very helpful for me. Now all works fine
