### ISSUE TITLE
Provide new style config setting for lock prefix

### ISSUE THREAD

**Issue by heanssgen-troy** [rabbitmq/rabbitmq-peer-discovery-consul#16]
Right now the only way to configure the consul lock prefix is by either setting the CONSUL_LOCK_PREFIX environment variable or using the old-style configuration (consul_lock_prefix key).

It might be useful to expose this configuration option as part of the sysctl 'new-style' mappings that are used in the rabbitmq 3.7.7 documentation, as this provides a much easier way of dynamically creating the configuration files.

For reference, this is not an exposed setting in https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/blob/master/priv/schema/rabbitmq_peer_discovery_consul.schema

**Comment by lukebakken** [comment]
We'd be happy to review a PR, too, if you're so inclined.

**Comment by heanssgen-troy** [comment]
Absolutely able to do this, however you will need to give me a few days to
learn erlang :)

Troy

**Comment by lukebakken** [comment]
Very little Erlang needed for this. Basically, you add the setting to the schema file to which you linked, and add a test or two [here](https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/blob/master/test/config_schema_SUITE_data/rabbitmq_peer_discovery_consul.snippets). To run just the schema tests, you can execute this command:

```
make ct-config_schema
```

Just make sure Erlang is installed and in your `PATH`. Thanks!

**Comment by hairyhum** [comment]
Should this change be documented [on the website](http://www.rabbitmq.com/cluster-formation.html#peer-discovery-consul)?

**Comment by michaelklishin** [comment]
It's not in a GA release yet so we can submit a doc PR and wait.
