### ISSUE TITLE
HTTP requests to Consul time out when plugin tries to acquire a lock

### ISSUE THREAD

**Issue by dfredell** [rabbitmq/rabbitmq-peer-discovery-consul#30]
I'm having troubles booting rabbitmq for the first time. I'm new to rabbitmq and rabbitmq-peer-discovery-consul. 

Versions
```
Docker rabbitmq:3.7-management-alpine
Local consul v1.4.4 running in agent mode
3 node server cluster of consul v1.4.4
```

/etc/rabbitmq/rabbitmq.conf
```
# Use consul for peer discovery, defaults to localhost
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_consul

# Set logging level
log.console.level = debug
```
/etc/rabbitmq/enabled_plugins
```
[rabbitmq_management,rabbitmq_peer_discovery_consul].
```
The output shows the the kv failed to lock.
```
2019-05-02 16:11:19.521 [info] <0.259.0> Will try to lock with peer discovery backend rabbit_peer_discovery_consul
2019-05-02 16:11:19.521 [debug] <0.259.0> PUT http://localhost:8500/v1/session/create [[]] [<<"{\"Name\":\"rabbit@148f1a13243c\",\"TTL\":\"30s\"}">>]
2019-05-02 16:11:19.526 [debug] <0.259.0> Response: [{ok,{{"HTTP/1.1",200,"OK"},[{"date","Thu, 02 May 2019 16:11:19 GMT"},{"vary","Accept-Encoding"},{"content-length","45"},{"content-type","application/json"}],"{\"ID\":\"e2ea0096-49db-0b75-c6a0-7f2ed326a597\"}"}}]
2019-05-02 16:11:19.527 [debug] <0.259.0> Starting session renewal
2019-05-02 16:11:19.527 [debug] <0.259.0> PUT http://localhost:8500/v1/kv/rabbitmq/default/startup_lock?acquire=e2ea0096-49db-0b75-c6a0-7f2ed326a597 [[]] [[]]
2019-05-02 16:11:21.778 [debug] <0.259.0> Response: [{error,timeout}]
2019-05-02 16:11:21.778 [debug] <0.259.0> HTTP Error timeout
2019-05-02 16:11:21.778 [error] <0.259.0> Failed to lock with peer discovery backend rabbit_peer_discovery_consul: "Error while acquiring lock, reason: timeout"
```
Looking at the consul docs, the command looks correct https://www.consul.io/api/kv.html#create-update-key
But looking in the consul ui I can see the kv was successfully locked. 
![image](https://user-images.githubusercontent.com/8085744/57090681-fae5c080-6ccc-11e9-8d77-a15b0161ff95.png)

I'm also able to run the consul lock command from the rabbitmq box just fine. 
```bash
bash-4.4# curl -X PUT http://localhost:8500/v1/kv/rabbitmq/default/startup_lock?acquire=e8e35e56-762c-d104-8e7b-662f1b70aa90
truebash-4.4# 
```

**Comment by lukebakken** [comment]
You can see that the timeout value is just over 2 seconds:

```
2019-05-02 16:11:19.527 [debug] <0.259.0> PUT http://localhost:8500/v1/kv/rabbitmq/default/startup_lock?acquire=e2ea0096-49db-0b75-c6a0-7f2ed326a597 [[]] [[]]
2019-05-02 16:11:21.778 [debug] <0.259.0> Response: [{error,timeout}]
```

Corresponding to [this default](https://github.com/rabbitmq/rabbitmq-peer-discovery-common/blob/master/include/rabbit_peer_discovery.hrl#L17-L22).

I just did some code analysis and there's no way at this time to increase the timeout beyond 2250ms. I will file an issue for that. In the meantime, anything you can do to speed up how long locking takes in your consul environment will probably resolve this issue.

**Comment by dfredell** [comment]
@lukebakken 
Thanks for the quick reply. I was looking for a config for the default timeout also, and couldn't find it. 

Although, I don't think increasing the time out will help much. The rabbitmq boot process goes in a loop trying again every 10 seconds. 

When I do my curl it comes back in 0.022s.
```bash
bash-4.4# time curl -X PUT http://localhost:8500/v1/kv/rabbitmq/default/startup_lock?acquire=8f7f77a4-95de-399d-be43-5d8986ab37fc 
true
real    0m0.022s
user    0m0.007s
sys     0m0.008s
```

**Comment by lukebakken** [comment]
That is very surprising, since `httpc` is doing the exact same thing as `curl`. If you have the time to do a packet capture on port `8500` for both requests I may be able to see what is different.

**Comment by dfredell** [comment]
Side note: When I used DNS to peer discover rabbitmq booted just fine. 

```properties
# Use consul for peer discovery, defaults to localhost
# not working: https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/issues/30
#cluster_formation.peer_discovery_backend = rabbit_peer_discovery_consul

# Use DNS for peer discovery, defaults to localhost
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_dns
cluster_formation.dns.hostname = rabbitmq.service.consul
```


Sure I can capture some packets.

**Comment by dfredell** [comment]
So on my platform, which is Joyent's Triton and docker, I'm unable to tcpdump the localhost nic. 
So I pointed rabbitmq's consul at the consul server cluster via `cluster_formation.consul.host = consul.service.consul`

Here is the log. Now the consul discovery doesn't get as far, but looking in the capture file the consul server replied within 10ms.

```
2019-05-02 17:57:15.362 [info] <0.218.0> Will try to lock with peer discovery backend rabbit_peer_discovery_consul
2019-05-02 17:57:15.362 [debug] <0.218.0> PUT http://consul.service.consul:8500/v1/session/create [[]] [<<"{\"Name\":\"rabbit@75d2eccbd453\",\"TTL\":\"30s\"}">>]
2019-05-02 17:57:17.618 [debug] <0.218.0> Response: [{error,timeout}]
2019-05-02 17:57:17.618 [debug] <0.218.0> HTTP Error timeout
2019-05-02 17:57:17.618 [error] <0.218.0> Failed to lock with peer discovery backend rabbit_peer_discovery_consul: "Error while creating a session, reason: timeout"
```
[rabbit.cap.txt](https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/files/3139355/rabbit.cap.txt)

**Comment by michaelklishin** [comment]
> When I used DNS to peer discover rabbitmq booted just fine

I'm not sure what this plugin can do about HTTP request timeouts. Honestly this feels like an environment-specific problem to me and belongs to the mailing list.

**Comment by michaelklishin** [comment]
OK, this is a side effect of https://github.com/rabbitmq/rabbitmq-peer-discovery-aws/issues/25 to answer my question in the above comment: there should be a way to override the timeout for individual peer discovery implementations such as this one.

**Comment by michaelklishin** [comment]
@lukebakken I filed #30 for one specific thing that we can address in this plugin. I suggest that the investigation as to what affects request latency on Joyent Triton with Docker is continued on the mailing list.

**Comment by dfredell** [comment]
Thanks @michaelklishin and @lukebakken for looking into this. I have posted this question on the mailing list https://groups.google.com/forum/#!topic/rabbitmq-users/kbprD9IFEnI

**Comment by lukebakken** [comment]
@michaelklishin there is still some issue in our code, or how we use `httpc`. Looking at the packet capture, you can see the almost immediate response, and at the 2251ms mark the connection is closed. Presumably this is when `timeout` is returned in the code, even though the response was received.

**Comment by lukebakken** [comment]
@dfredell when you run `curl` to test the same request, could you please add `-vvv` to the arguments, capture everything to a file, and attach it here? I'm wondering what headers `curl` adds.

**Comment by dfredell** [comment]
From https://groups.google.com/forum/#!topic/rabbitmq-users/kbprD9IFEnI 
Luke,
When running on my local Docker on Ubuntu consul and RabbitMQ work as well as the test erl commands. I will raise a ticket with our Joyent Triton support team. Thanks for your help. I'll let you know how it goes with them. It appears to be something with erlang and Triton Docker, since the cURL commands work fine.

**Comment by lukebakken** [comment]
Thanks. If you find out something useful, please follow up!

**Comment by dfredell** [comment]
In my conversation with Joyent we were able to reproduce this bug. It turned out to be caused by [OS-7107](https://smartos.org/bugview/OS-7107). I was hitting this bug on [Platform Image](https://docs.joyent.com/private-cloud/platform-images) 20190228T233723Z and when I upgraded to 20190228T233723Z which has the OS-7107 fix, this bug went away. OS-7107 was originally released in [20190117T065704Z](https://us-east.manta.joyent.com/Joyent_Dev/public/SmartDataCenter/release-20190117-20190117T065704Z/changelog.txt)

**Comment by lukebakken** [comment]
@dfredell thanks for the follow-up!
