### ISSUE TITLE
cluster_formation.consul.lock_prefix in rabbitmq.conf not respected

### ISSUE THREAD

**Issue by gmr** [rabbitmq/rabbitmq-peer-discovery-consul#32]
RabbitMQ 3.7.14

I'm trying to configure a base path for the lock prefix using `rabbitmq.conf`:

```toml
cluster_formation.consul.lock_prefix = locks/rabbitmq
```

But when I examine the auto-generated config from cuttlefish in `/var/lib/rabbitmq/config/generated/rabbitmq.config`, my config value is not specified:

```erlang
[ ...
{rabbit,
     [{cluster_formation,
          [{peer_discovery_backend,rabbit_peer_discovery_consul},
           {node_type,disc},
           {peer_discovery_consul,
               [{consul_host,"localhost"},
                {consul_port,8500},
                {consul_scheme,"http"},
                {consul_acl_token,"00000000000000"},
                {cluster_name,"common-rabbitmq"},
                {consul_svc,"common-rabbitmq"},
                {consul_svc_addr_auto,true},
                {consul_svc_addr_nodename,true},
                {consul_svc_ttl,30},
                {consul_deregister_after,90},
                {consul_use_longname,true},
                {consul_svc_tags,["amqp"]},
                {consul_lock_prefix,"common-rabbitmq-autocluster"}
...
]```

Looking at `/var/lib/rabbitmq/schema/rabbitmq_peer_discovery_consul.schema`:

```erlang
%% lock key prefix

{mapping, "cluster_formation.consul.lock_prefix", "rabbit.cluster_formation.peer_discovery_consul.consul_lock_prefix", [
    {datatype, string}
]}.

{translation, "rabbit.cluster_formation.peer_discovery_consul.consul_lock_prefix",
fun(Conf) ->
    case cuttlefish:conf_get("cluster_formation.consul.lock_prefix", Conf, undefined) of
        undefined -> cuttlefish:unset();
        Value     -> Value
    end
end}.
```

it looks right to me so I'm not sure what I'm doing wrong here. Is this PEBCAK or is something off in the cuttlefish schema? The rest of the settings apply cleanly.

**Comment by michaelklishin** [comment]
There is a test case for [lock_prefix](https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/blob/master/test/config_schema_SUITE_data/rabbitmq_peer_discovery_consul.snippets#L174).

**Comment by michaelklishin** [comment]
`common-rabbitmq-autocluster` is not a value I could find in any of our repositories. I suspect that you may have an environment variable exported that also sets lock prefix to a different value. Those [take precedence](https://github.com/rabbitmq/rabbitmq-peer-discovery-common/blob/master/src/rabbit_peer_discovery_config.erl#L67) over config values (likely because that's how `rabbitmq-autocluster` did it).

**Comment by gmr** [comment]
is a pebcak, the key was set twice. Sorry to bother!

**Comment by michaelklishin** [comment]
@gmr just for my personal curiosity, was my hypothesis correct?

**Comment by gmr** [comment]
No, I had the value defined twice in the config:

```
cluster_formation.consul.lock_prefix = locks/rabbitmq
...
cluster_formation.consul.lock_prefix = common-rabbitmq-autocluster
```
Thanks for the quick investigation though, I hate creating false alarms.
