### ISSUE TITLE
How the heck do you install this?

### ISSUE THREAD

**Issue by luckytaxi** [rabbitmq/rabbitmq-peer-discovery-consul#6]
I installed rabbitmq-server via RPM on mu Centos 7 node. I want to use this plugin for auto clustering. Where do I even begin?

**Comment by lukebakken** [comment]
Hello -

Please use [the mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) for questions. The RabbitMQ team does not use GitHub issues for discussions. Thanks!

Having said that, searching Google with `site:rabbitmq.com cluster` lead me to this document:

https://www.rabbitmq.com/cluster-formation.html

**Comment by luckytaxi** [comment]
Whooops. looks like it's included w/ the default install!
