### ISSUE TITLE
Allow setting initial health-check status on registration

### ISSUE THREAD

**Issue by andersenleo** [rabbitmq/rabbitmq-peer-discovery-consul#8]
We're running RabbitMQ in a GCP managed instance group and frequently run into a situation where no, or only some, members form a cluster. This seems to be related to how the health-check behaves on service-registration in Consul.

The plugin uses a key-value lock in Consul to make sure that only one member registers and lists peer services. This seems to work. 

When a rabbitmq service gets registered in Consul the default state for that service is "critical". This is the case until the first TTL pass is sent (by default after 15 seconds). When multiple peers starts simultaneous they will not discover other peers since the service registration is in state "critical" for 15 seconds or so.

It is possible to set an initial state for a service registration in Consul (`Status` in `/agent/check/register`). If it was possible to set this to "passing" on registration I imagine that the peers would be able to form a cluster even if they start up at the same time.

So - a suggestion is to add a configuration option (`cluster_formation.consul.svc_initial_status` or similar) to control this behaviour.

**Comment by michaelklishin** [comment]
Thanks for the details. What should the default value be, "passing"?

**Comment by michaelklishin** [comment]
Never mind, I re-read the problem definition and "passing" seems to be the only initial value that would help.

Note that there is `include_nodes_with_warnings` which, when set to `true`, should act as a workaround but it increases the chances of new nodes clustering with a problematic and soon-to-be-removed one.

**Comment by andersenleo** [comment]
We did try with the `include_nodes_with_warnings` - but as far as I can tell, the initial status is `critical` for the service.  I'm not sure when the service will end up in a `warning` state, but that's not the initial state.

Thanks for having a look at it 👍 Were my Erlang skills slightly better I might have attempted a PR :-)

**Comment by michaelklishin** [comment]
No worries, you have already done all the hard work of figuring out what exactly is going on and why :)

**Comment by michaelklishin** [comment]
FTR, the feature is covered in [Initial Health Check Status](https://www.consul.io/docs/agent/checks.html#initial-health-check-status).
